---
 - name: Deploy the project on Ubuntu
   git: repo=https://github.com/anandreddyr11/SAB.git dest=/var/www/html/ update=no
   when: ansible_distribution == "Ubuntu"
   notify:
    - Restart Ubuntu Apache

